[package]
name = "semver-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro-error = "1"
semver = "1"
syn = { version = "2", features = ["parsing"] }
