reorder_imports = true

# only available with nightly :(
#unstable_features = true
#force_multiline_blocks = true
#group_imports = "StdExternalCrate"
#format_code_in_doc_comments = true
#imports_granularity = "Crate"
#wrap_comments = true
#control_brace_style = "ClosingNextLine"
#imports_layout = "Vertical"

